services:
  nginx-proxy-manager:
    image: 'docker.io/jc21/nginx-proxy-manager:latest'
    container_name: nginx-proxy-manager
    cap_add:
      - NET_ADMIN
    environment:
      DISABLE_IPV6: true
    networks:
      net:
        ipv4_address: 192.168.1.222
    ports:
      - 49152:80 # Public HTTP Port
      - 443:443  # Public HTTPS Port
      - 81:81    # Admin Web Port
    volumes:
      - /home/jonathan/data/dns/data:/data
      - /home/jonathan/data/dns/letsencrypt:/etc/letsencrypt
    restart: unless-stopped

networks:
  net:
    driver: macvlan
    driver_opts:
      parent: eth0
    ipam:
      config:
        - subnet: 192.168.1.0/24 # your router's address range
          gateway: 192.168.1.1   # NOTE: lack of dash is significant

# Defaults:
# Email:    admin@example.com
# Password: changeme
